/**
 * Tile Kings - Mana & Land Engine
 * Manages orthogonal connected land flood-fill, HP calculation, elemental mana generation, and starvation tracking.
 */

import { GRID_SIZE, isInBounds } from './gridEngine.js';

/**
 * Finds all connected land regions on the board using orthogonal flood fill.
 * Neutral terrain is ignored.
 * @param {Array<Array<Object>>} boardGrid 12x12 array of cell objects { x, y, terrain: 'neutral'|'fire'|'earth'|'water'|'air' }
 * @returns {Array<Object>} List of regions: { id, element, tiles: [{x,y}], tileCount }
 */
export function getConnectedLandRegions(boardGrid) {
  const visited = Array.from({ length: GRID_SIZE }, () => Array(GRID_SIZE).fill(false));
  const regions = [];
  let regionCounter = 0;

  const neighbors = [
    { dx: 1, dy: 0 },
    { dx: -1, dy: 0 },
    { dx: 0, dy: 1 },
    { dx: 0, dy: -1 }
  ];

  for (let r = 0; r < GRID_SIZE; r++) {
    for (let c = 0; c < GRID_SIZE; c++) {
      const cell = boardGrid[r][c];
      const terrain = cell.terrain;

      if (terrain !== 'neutral' && !visited[r][c]) {
        // Start flood fill for this connected region
        const regionTiles = [];
        const queue = [{ x: c, y: r }];
        visited[r][c] = true;

        while (queue.length > 0) {
          const current = queue.shift();
          regionTiles.push(current);

          for (const n of neighbors) {
            const nx = current.x + n.dx;
            const ny = current.y + n.dy;

            if (isInBounds(nx, ny) && !visited[ny][nx]) {
              const neighborCell = boardGrid[ny][nx];
              if (neighborCell.terrain === terrain) {
                visited[ny][nx] = true;
                queue.push({ x: nx, y: ny });
              }
            }
          }
        }

        regionCounter++;
        regions.push({
          id: `region_${regionCounter}_${terrain}`,
          element: terrain,
          tiles: regionTiles,
          tileCount: regionTiles.length
        });
      }
    }
  }

  return regions;
}

/**
 * Calculates mana generation for a round based on board regions and piece positions.
 * @param {Array<Array<Object>>} boardGrid 12x12 board state
 * @param {Object} piecesMap Map of all pieces in play
 * @returns {Object} { whiteMana: { fire, earth, water, air }, blackMana: { fire, earth, water, air }, logs: [] }
 */
export function calculateGenerationPhaseMana(boardGrid, piecesMap) {
  const regions = getConnectedLandRegions(boardGrid);

  const whiteMana = { fire: 0, earth: 0, water: 0, air: 0 };
  const blackMana = { fire: 0, earth: 0, water: 0, air: 0 };
  const calculationLogs = [];

  for (const region of regions) {
    const element = region.element; // 'fire', 'earth', 'water', 'air'
    const tileCount = region.tileCount;

    // Calculate current HP of White and Black pieces standing on this region
    let whiteHP = 0;
    let blackHP = 0;

    const occupantSummary = [];

    for (const tile of region.tiles) {
      const pieceOnTile = Object.values(piecesMap).find(p => p.x === tile.x && p.y === tile.y && p.hp > 0);
      if (pieceOnTile) {
        if (pieceOnTile.owner === 'white') {
          whiteHP += pieceOnTile.hp;
          occupantSummary.push(`White ${pieceOnTile.name} (${pieceOnTile.hp} HP)`);
        } else if (pieceOnTile.owner === 'black') {
          blackHP += pieceOnTile.hp;
          occupantSummary.push(`Black ${pieceOnTile.name} (${pieceOnTile.hp} HP)`);
        }
      }
    }

    let generatingPlayer = null;
    let effectiveHP = 0;

    if (whiteHP > blackHP) {
      generatingPlayer = 'white';
      effectiveHP = whiteHP - blackHP;
    } else if (blackHP > whiteHP) {
      generatingPlayer = 'black';
      effectiveHP = blackHP - whiteHP;
    } else {
      // Equal HP or 0 HP on both sides -> 0 mana
      generatingPlayer = null;
      effectiveHP = 0;
    }

    const manaGenerated = Math.floor(Math.min(tileCount, effectiveHP) / 2);

    if (generatingPlayer && manaGenerated > 0) {
      if (generatingPlayer === 'white') {
        whiteMana[element] += manaGenerated;
      } else {
        blackMana[element] += manaGenerated;
      }

      calculationLogs.push(
        `Region [${element.toUpperCase()}] (${tileCount} tiles): White HP=${whiteHP}, Black HP=${blackHP} => ${generatingPlayer.toUpperCase()} generates ${manaGenerated} ${element.toUpperCase()} mana.`
      );
    } else {
      calculationLogs.push(
        `Region [${element.toUpperCase()}] (${tileCount} tiles): White HP=${whiteHP}, Black HP=${blackHP} => 0 mana generated.`
      );
    }
  }

  return {
    whiteMana,
    blackMana,
    regions,
    logs: calculationLogs
  };
}

/**
 * Checks and updates Starvation Counters at the end of Generation Phase.
 * @param {number} whiteTotalMana Total mana generated by White this phase
 * @param {number} blackTotalMana Total mana generated by Black this phase
 * @param {number} currentWhiteStarvation Current White starvation strikes (0..2)
 * @param {number} currentBlackStarvation Current Black starvation strikes (0..2)
 * @returns {Object} { whiteStarvation, blackStarvation, whiteLost, blackLost, logs }
 */
export function evaluateManaStarvation(whiteTotalMana, blackTotalMana, currentWhiteStarvation, currentBlackStarvation) {
  let nextWhiteStarvation = currentWhiteStarvation;
  let nextBlackStarvation = currentBlackStarvation;
  const logs = [];

  // White Starvation rule: 0 mana AND Black >= 1 mana
  if (whiteTotalMana === 0 && blackTotalMana > 0) {
    nextWhiteStarvation++;
    logs.push(`⚠️ WHITE generated 0 mana while Black generated ${blackTotalMana} mana! White Starvation strike ${nextWhiteStarvation}/2.`);
  } else {
    // Generating any amount of mana resets starvation counter to 0
    nextWhiteStarvation = 0;
  }

  // Black Starvation rule: 0 mana AND White >= 1 mana
  if (blackTotalMana === 0 && whiteTotalMana > 0) {
    nextBlackStarvation++;
    logs.push(`⚠️ BLACK generated 0 mana while White generated ${whiteTotalMana} mana! Black Starvation strike ${nextBlackStarvation}/2.`);
  } else {
    nextBlackStarvation = 0;
  }

  const whiteLost = nextWhiteStarvation >= 2;
  const blackLost = nextBlackStarvation >= 2;

  if (whiteLost) logs.push(`💀 WHITE LOSES via Mana Starvation (2 consecutive failed Generation Phases)!`);
  if (blackLost) logs.push(`💀 BLACK LOSES via Mana Starvation (2 consecutive failed Generation Phases)!`);

  return {
    whiteStarvation: nextWhiteStarvation,
    blackStarvation: nextBlackStarvation,
    whiteLost,
    blackLost,
    logs
  };
}
